### PR TITLE
Get project working on Windows

### LINKED ISSUE #13: Project not building on Windows
I was interested in playing around with this gem but I develop primarily on a Windows machine and this project does not seem to work on it. It looks like that is because you test with Aruba and Aruba does not (currently) work on Windows. Even with an unreleased Aruba fix, about half of the tests fail because of line endings. I might attempt to fix all of this myself in the near future.

### PR DESCRIPTION
**Pull request by enkessler**
This fixes #13

### CODE REVIEW

**Comment by enkessler** [comment]
@lindt Bump.

**Comment by enkessler** [comment]
@lindt :(

**Comment by lindt** [comment]
sorry for late reply.....nice change! awesome.

Do you know how to get CI support for windows?

**Comment by enkessler** [comment]
It's as easy as having an [Appveyor](https://ci.appveyor.com/project/enkessler/cuke-modeler/branch/dev) account and having a [config file](https://github.com/enkessler/cuke_modeler/blob/master/appveyor.yml) in the project.

**Comment by enkessler** [comment]
@lindt If you can set up the Appveyor account for the project, I can handle the configuration side.

**Pull request merged**
